categories:
  - title: '🐞 Bugs'
    labels:
      - 'bug'
  - title: '🚀 Enhancements'
    labels:
      - 'enhancement'
  - title: '🧰 Maintenance'
    label:
      - 'dependencies'
category-template: "### $TITLE"
template: |
  ## What’s Changed

  $CHANGES

  See also: [Documentation](https://swiftpackageindex.com/request-dl/request-dl/main/documentation/requestdl)
