name: Documentation

on:
  workflow_call:
    inputs:
      swift-version:
        required: true
        type: string
      target:
        required: true
        type: string
      hosting-base-path:
        required: true
        type: string
      output:
        required: true
        type: string
      platform:
        default: 'macOS-latest'
        required: false
        type: string

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ${{ inputs.platform }}
    steps:
      - name: ⬇️ Get Sources
        uses: actions/checkout@v3.5.3

      - name: ☑️ Swift Select
        uses: swift-actions/setup-swift@v1
        with:
            swift-version: ${{ inputs.swift-version}}

      - name: Setup Pages
        uses: actions/configure-pages@v3.0.6

      - name: Swift DocC Action
        uses: fwcd/swift-docc-action@v1.0.2
        with:
          target: ${{ inputs.target }}
          output: ${{ inputs.output }}
          hosting-base-path: ${{ inputs.hosting-base-path }}
          disable-indexing: 'true'
          transform-for-static-hosting: 'true'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          path: ${{ inputs.output }}

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2.0.2
