name: Swiftlint

on:
  workflow_call:

jobs:
  lint:
    runs-on: macOS-latest
    steps:
      - name: ⬇️ Get Sources
        uses: actions/checkout@v3.5.3

      - name: Install swiftlint
        run: >
          if [[ ! -f "/usr/local/bin/swiftlint" ]]
             then
               brew install swiftlint
             fi

      - name: Swiftlint
        run: swiftlint lint
